# Generated by Django 4.0.4 on 2022-05-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('TicketID', models.AutoField(primary_key=True, serialize=False)),
                ('TicketName', models.CharField(max_length=100)),
                ('Description', models.TextField(max_length=250)),
                ('Status', models.CharField(choices=[('0', 'COMPLETE'), ('1', 'UNCOMPLETE'), ('2', 'REQUIRE_REVIEW')], max_length=1)),
                ('IssueDate', models.DateTimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.user')),
            ],
        ),
        migrations.CreateModel(
            name='Chatroom',
            fields=[
                ('ChatroomID', models.AutoField(primary_key=True, serialize=False)),
                ('ChatMessage', models.CharField(max_length=200)),
                ('SentTime', models.DateTimeField(auto_now_add=True)),
                ('TicketID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.ticket')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='login.user')),
            ],
        ),
    ]
